name: Lint, Test, Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Deploy Code
        run: echo "Deploying..."
